// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynfgfypevkfosdwvonyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluZmdmeXBldmtmb3Nkd3Zvbnl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NzMwNjQsImV4cCI6MjA2MjA0OTA2NH0.S506Eu61bg5159F6kx_Pi7CWszf2LYDYLiKau4edj7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);